spring:
  datasource:
    url: jdbc:h2:file:~/UserDB;FILE_LOCK=FS;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    use_sql_comments: true
    format_sql: true

server:
  port: 9000