server:
  port: 8081

management:
  data:
    mongodb:
      user: admin
      password: admin
      uri: cluster0.fpiga.mongodb.net/test
ambrustorok:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000