server:
  port: 8080

zuul:
  routes:
    vehicle-service:
      path: /vehicle-service/**
      url: http://127.0.0.1:8082/
    auth-server:
      path: /auth-server/**
      url: http://127.0.0.1:8081/
