server:
  port: 8080

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    car-service:
      path: /car-service/**
      url: http://127.0.0.1:8082/
    auth-server:
      path: /auth-server/**
      url: http://localhost:9000/oauth2
