zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    vehicle-api:
      path: /vehicle-api/**
      url: http://localhost:8088
    search-api:
      path: /search-api/**
      url: http://localhost:8089
    oauth:
      path: /oauth2/**
      url: http://localhost:9000/oauth2