# A Config server altal kiszolgalt local-dev profilhoz tartozo beallitasok, ezt MINDEN alkalmazas megkapja
cs:
  auth-sever-url: http://localhost:9000/oauth2
  client-id: car-searcher-frontend
  client-secret: ca8831eb-e504-46f1-a514-8be84ba892ed

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks